FROM python:3.10-slim


COPY requirements_train.txt /app/requirements_train.txt

RUN apt-get update && \
    apt-get install -y libexpat1 git && \
    pip install --no-cache-dir torch torchvision  && \
    pip install --no-cache-dir -r /app/requirements_train.txt && \
    rm -rf /var/lib/apt/lists/*
